name: TFLint
on: [push]
jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive

  lint_aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws
    steps:
      - uses: actions/checkout@v5
      - uses: terraform-linters/setup-tflint@v4
      - run: tflint --init
      - run: tflint --format compact

  test_aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform test

  lint_azure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: azure
    steps:
      - uses: actions/checkout@v5
      - uses: terraform-linters/setup-tflint@v4
      - run: tflint --init
      - run: tflint --format compact
